.\" Header and footer
.TH "MATCH\-GET_ACTIONS" "1" "" "MATCH Tool" "MATCH Manual"

.\" Name and brief description
.SH "NAME"
match\-get_actions \- Display actions in the pipeline

.\" Options, brief
.SH SYNOPSIS
.nf
\fImatch get_actions\fR [\-f <family>] [\-p <pid>] [\-g] [\-h] [\-i ifname] [\-s]
.fi

.\" Detailed description
.SH DESCRIPTION
Display the actions supported by the pipeline.

.\" Options, detailed
.SH OPTIONS

.br
\-f <family>
.RS 4
The netlink family used by the MATCH daemon.
.RE

.br
\-p <pid>
.RS 4
The pid of the MATCH daemon (e.g. `pidof lt-matchd`).
.RE

.br
\-g
.RS 4
Display graphs in DOT format.
.RE

.br
\-i <ifname>
.RS 4
Specify interface name (e.g. eth0)
.RE

.br
\-s
.RS 4
Silence verbose printing
.RE
