.\" Header and footer
.TH "MATCH\-LPORT_LOOKUP" "1" "" "MATCH Tool" "MATCH Manual"

.\" Name and brief description
.SH "NAME"
match\-lport_lookup \- Lookup a logical port number of PCI device

.\" Options, brief
.SH SYNOPSIS
.nf
\fImatch lport_lookup\fR [\-f <family>] [\-p <pid>] [\-g] [\-h] [\-i ifname] [\-s]
            (pci <BUS:DEVICE.FUNCTION> | mac <MACADDR>)
.fi

.\" Detailed description
.SH DESCRIPTION
Send a command instructing a match action table (MAT) daemon to lookup and respond with the logical port number associated with a given PCI device or MAC address.
.sp
The logical port number can be used in matches and actions taking a port number as a parameter.

.\" Options, detailed
.SH OPTIONS

.br
\-f <family>
.RS 4
The netlink family used by the MAT daemon.
.RE

.br
\-p <pid>
.RS 4
The pid of the MATCH daemon (e.g. `pidof lt-matchd`).
.RE

.br
\-g
.RS 4
Display graphs in DOT format.
.RE

.br
\-i <ifname>
.RS 4
Specify interface name (e.g. eth0)
.RE

.br
\-s
.RS 4
Silence verbose printing
.RE

.br
pci <BUS:DEVICE.FUNCTION>
.RS 4
The PCI bus, device, and function numbers of the device.
.RE

.br
mac <MACADDR>
.RS 4
The MAC address of the device.
.RE
